// Portfolio projecten data - gedeeld tussen Hero en portfolio pagina's
// Volgorde is gemixt zodat donkere en lichte mockups afwisselen
export const projects = [
	{
		id: "velvet-bistro",
		title: "Velvet Bistro",
		category: "Restaurant",
		description: "Een modern restaurant met focus op lokale ingrediënten en seizoensgebonden gerechten. De website combineert elegantie met gebruiksgemak.",
		image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
		services: ["Website Design", "Online Reserveringen", "Menu Beheer"],
		year: "2025",
		url: "velvetbistro.nl",
	},
	{
		id: "artisan-bakery",
		title: "Artisan Bakery",
		category: "Bakkerij",
		description: "Ambachtelijke bakkerij met online besteloptie. Klanten kunnen vooraf bestellen en ophalen.",
		image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80",
		services: ["Website", "Bestelformulier", "Producten"],
		year: "2024",
		url: "artisanbakery.nl",
	},
	{
		id: "neon-studio",
		title: "Neon Studio",
		category: "Creative Agency",
		description: "Creatief bureau gespecialiseerd in branding en digitale ervaringen. Een gedurfde website die hun creatieve visie weerspiegelt.",
		image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
		services: ["Branding", "Web Design", "Motion Design"],
		year: "2025",
		url: "neonstudio.nl",
	},
	{
		id: "daan-buurs-photography",
		title: "Daan Buurs Photography",
		category: "Fotograaf Portfolio",
		description: "Minimalistisch portfolio voor fashion en portrait fotograaf. Focus op beeldmateriaal met strak design.",
		image: "https://images.unsplash.com/photo-1554048612-b6a482bc67e5?w=800&q=80",
		services: ["Portfolio Website", "Galerij", "Contact"],
		year: "2025",
		url: "daanbuurs.nl",
	},
	{
		id: "urban-apparel",
		title: "Urban Apparel",
		category: "Fashion Webshop",
		description: "Streetwear webshop met focus op duurzame mode. Complete e-commerce oplossing met stijlvolle uitstraling.",
		image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
		services: ["Webshop", "Lookbook", "Size Guide"],
		year: "2025",
		url: "urbanapparel.nl",
	},
	{
		id: "vanderberg-advocaten",
		title: "Van der Berg Advocaten",
		category: "Advocatenkantoor",
		description: "Gerenommeerd advocatenkantoor gespecialiseerd in ondernemingsrecht. Professionele uitstraling met focus op vertrouwen.",
		image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
		services: ["Website", "Team Pagina", "Expertise Overzicht"],
		year: "2024",
		url: "vanderbergadvocaten.nl",
	},
	{
		id: "iron-athletics",
		title: "Iron Athletics",
		category: "Sportschool",
		description: "Premium sportschool met personal training en groepslessen. Online ledenportaal en lesrooster systeem.",
		image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80",
		services: ["Ledenportaal", "Rooster Systeem", "Online Betaling"],
		year: "2024",
		url: "ironathletics.nl",
	},
	{
		id: "mode-atelier",
		title: "Mode Atelier",
		category: "Fashion Designer",
		description: "Luxury fashion designer portfolio met bold typography en editorial fotografie.",
		image: "https://images.unsplash.com/photo-1558769132-cb1aea1c8a8d?w=800&q=80",
		services: ["Portfolio", "Lookbook", "About"],
		year: "2025",
		url: "modeatelier.nl",
	},
];

export type Project = typeof projects[number];
